confluence_space_name: "test"
confluence_space_home_page_name: 'test Home'
confluence_name_of_root_directory: 'Atomic Threat Coverage'
md_name_of_root_directory: 'Atomic_Threat_Coverage'
detection_rules_directory: '../detectionrules'
triggering_directory: '../triggering/atomic-red-team/atomics'
confluence_rest_api_url: 'https://atomicthreatcoverage.atlassian.net/wiki/rest/api/'
sigmac_path: '../detectionrules/sigma/tools/sigmac'