confluence_space_name: "LOL" # SPACE KEY. GO TO: SPACE TOOLS -> Overview -> Space Details -> Key
confluence_space_home_page_name: 'lol'
confluence_name_of_root_directory: 'Atomic Threat Coverage'
md_name_of_root_directory: 'Atomic_Threat_Coverage'
detection_rules_directory: '../detection_rules'
triggers_directory: '../triggers/atomic-red-team/atomics'
confluence_rest_api_url: 'http://confluence.yugoslavskiy.local:8090/rest/api/'
sigmac_path: '../detection_rules/sigma/tools/sigmac'
